- hosts: controllers
  remote_user: ubuntu
  tasks:
   - name: Create etcd directory
     become: true
     become_user: root
     file:
       path: /etc/etcd/
       state: directory
       recurse : yes

   - name: Copies pem files to /etc/etcd/
     become: true
     become_user: root
     copy:
       src: "{{ item.0 }}"
       dest: /etc/etcd/
       remote_src: true
     with_together:
       - [ '/home/ubuntu/ca.pem', '/home/ubuntu/kubernetes.pem', '/home/ubuntu/kubernetes-key.pem' ]

   - name: Download etcd binary
     get_url:
       url: https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz
       dest: /home/ubuntu

   - name: Extract etcd binaries
     command: tar -xvzf /home/ubuntu/etcd-v3.0.10-linux-amd64.tar.gz

   - name: Move to etcd to /usr/bin
     become: true
     become_user: root
     command: mv /home/ubuntu/etcd-v3.0.10-linux-amd64/etcd /usr/bin/

   - name: Move to etcdctl to /usr/bin
     become: true
     become_user: root
     command:  mv /home/ubuntu/etcd-v3.0.10-linux-amd64/etcdctl /usr/bin/

   - name: Create etcd data directory
     become: true
     become_user: root
     file:
       path: /var/lib/etcd
       state: directory
       recurse : yes

   - name: copies local etcd.service template to remote
     copy:
       src: etcd.service
       dest: /home/ubuntu

   - name: Set INTERNAL IP - not working
     shell: "echo $INTERNAL_IP"
     environment:
       INTERNAL_IP: $(curl -s https://169.254.169.254/latest/meta-data/loal-ipv4)

   - name: Echo internal ip - not working
     shell: "echo $INTERNAL_IP"

   - name: Set etcd name - not working
     shell: "echo $ETCD_NAME"
     environment:
       ETCD_NAME: controller$(echo $INTERNAL_IP | cut -c 11)

   - name: Echo etcd name - not working
     shell: "echo $ETCD_NAME"

# run the below command once the setup is run
# INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) && ETCD_NAME=controller$(echo $INTERNAL_IP | cut -c 11) && sed -i s/INTERNAL_IP/${INTERNAL_IP}/g etcd.service && sed -i s/ETCD_NAME/${ETCD_NAME}/g etcd.service && sudo mv etcd.service /etc/systemd/system/ && sudo systemctl daemon-reload && sudo systemctl enable etcd && sudo systemctl start etcd
